name: dotabase
services:
  db:
    image: mysql:5.7
    restart: always
    env_file: ".env"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPW}
    ports:
      - '3307:3306'
    volumes:
      - dotadb:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8083:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3307
volumes:
  dotadb: